import os

import torch
import torch.nn as nn

torch.set_default_dtype(torch.float32)


class EquityNet(nn.Module):
    # Lightweight MLP used by the CFR pipeline and the standalone equity trainer.
    def __init__(self, input_dim=106, hidden_dim=256):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, hidden_dim),
            nn.GELU(),
            nn.Linear(hidden_dim, hidden_dim),
            nn.GELU(),
            nn.Linear(hidden_dim, 1),
            nn.Sigmoid(),
        )

    def forward(self, inputs):
        return self.net(inputs)

class Config:
    # Runtime and hardware profile.
    SAFE_HARDWARE_MODE = True
    RUNTIME_PROFILE = 'stable'
    DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
    DTYPE = torch.float32
    NN_DTYPE = torch.float32

    # ROCm AMP policy: prefer bf16 when supported, otherwise fallback to fp16.
    AMP_ENABLED = True
    AMP_DTYPE = torch.bfloat16
    AMP_BF16_OPT_IN = True
    AMP_PREFER_BF16 = True
    USE_TORCH_COMPILE = False

    # Thread safety on ROCm + multiprocessing.
    OMP_NUM_THREADS = 1
    MKL_NUM_THREADS = 1
    TORCH_NUM_THREADS = 1
    CUDNN_BENCHMARK = False
    CUDNN_DETERMINISTIC = False

    # PPO core.
    NUM_ACTIONS = 3
    DEEP_CFR_FEATURE_DIM = 16
    STATE_DIM = 169
    MODEL_HIDDEN_DIM = 1024
    MODEL_DEPTH = 4
    MODEL_DROPOUT = 0.05
    GRADIENT_CHECKPOINTING = True
    MAX_GRAD_NORM = 5.0
    LOSS_CLAMP = 10.0
    PPO_EPOCHS = 6
    NUM_TRAINING_STEPS = 12
    PPO_MINIBATCHES = 8
    GRADIENT_ACCUMULATION_STEPS = 2
    CACHE_CLEAR_INTERVAL_STEPS = 0
    CLIP_EPS = 0.2
    VALUE_CLIP_ENABLED = False
    VALUE_CLIP_EPS = 0.2
    VALUE_COEF = 0.5
    ENTROPY_COEF = 0.015
    ENTROPY_FINAL_COEF = 0.008
    ENTROPY_DECAY_ITERS = 20000
    ENTROPY_DECAY_ENABLED = True
    GAE_LAMBDA = 0.95
    GAMMA = 0.995
    LEARNING_RATE = 2.5e-4
    WEIGHT_DECAY = 1e-4

    # Stable PPO defaults for the 7900 XT rig.
    STABLE_BATCH_SIZE = 8192
    STABLE_NUM_SIMULATIONS = 256
    STABLE_ROLLOUT_STEPS = 128
    STABLE_MP_PROCESSES = 16
    STABLE_VRAM_SOFT_LIMIT_GB = 14.5

    # Throughput and simulation.
    BATCH_SIZE = STABLE_BATCH_SIZE
    BATCH_SIZE_LADDER = (16384, 12288, 8192, 6144, 4096)
    MIN_BATCH_SIZE = 1024
    MAX_BATCH_SIZE = max(BATCH_SIZE_LADDER)
    RECOVERY_BATCH_CAP = STABLE_BATCH_SIZE
    ROLLOUT_SCALE_WITH_BATCH = False
    MAX_ROLLOUT_STEPS = 4096
    WARMUP_ENABLED = False
    WARMUP_TOTAL_ITERS = 0
    WARMUP_MIN_ROLLOUT_STEPS = 256
    WARMUP_MIN_NUM_SIMULATIONS = 128
    WARMUP_MIN_TRAINING_STEPS = 8
    NUM_SIMULATIONS = STABLE_NUM_SIMULATIONS
    NUM_SIMS = NUM_SIMULATIONS
    MIN_NUM_SIMULATIONS = 16
    MAX_NUM_SIMULATIONS = 1024
    NUM_BUCKETS = 128
    NUM_TRAVERSALS = 128
    MIN_NUM_TRAVERSALS = 16
    MAX_NUM_TRAVERSALS = 512
    MAX_CFR_DEPTH = 6
    START_MAX_DEPTH = 2
    ADVANTAGE_TRAIN_STEPS = 2
    STRATEGY_TRAIN_STEPS = 2
    SAMPLING_RATE = 1.0
    PRESSURE_SIMULATION_CAP = 64
    RECOVERY_SIMULATION_CAP = STABLE_NUM_SIMULATIONS
    ROLLOUT_STEPS = STABLE_ROLLOUT_STEPS
    ITERATIONS = 100000
    LOG_INTERVAL = 10

    # Curriculum and population training.
    START_OPPONENTS = 2
    TARGET_OPPONENTS = 6
    NUM_OPPONENTS = START_OPPONENTS
    CURRICULUM_INTERVAL = 2000
    POPULATION_SIZE = 6
    VALIDATION_INTERVAL = 250
    OPPONENT_DECAY = 0.98
    PBT_MUTATION_SCALE = 0.15
    POPULATION_MIX_PROB = 0.12
    POPULATION_MIX_MUTATION_SCALE = 0.05
    ELO_K_FACTOR = 24.0
    EXPLORATION_FACTOR = 0.12

    # Hybrid action logic.
    HYBRID_EQUITY_WEIGHT = 0.35
    MCTS_EQUITY_THRESHOLD = 0.65
    MCTS_TRIGGER_PROB = 0.15
    MCTS_MAX_DEPTH = 3
    MCTS_BRANCHING = 2
    MCTS_MAX_ACTIVE = 64
    MCTS_FUTURE_DISCOUNT = 0.35
    MCTS_VRAM_DISABLE_GB = 15.0
    EXPLOIT_AGGRESSION_THRESHOLD = 0.55
    EXPLOIT_RAISE_MULTIPLIER = 1.15
    PREFLOP_CHART_ENABLED = True

    # Game simulation constants.
    POT_SIZE = 100.0
    CALL_AMOUNT = 20.0
    RAISE_MULTIPLIER = 3.0
    FOLD_EQUITY_MEAN = 0.4
    FOLD_EQUITY_STD = 0.3
    EQUITY_STD = 0.1
    EQUITY_ROLLOUTS = 32
    MIN_EQUITY_ROLLOUTS = 2
    BLUFF_FACTOR = 0.2
    FOLD_PENALTY = 0.5
    UTILITY_CLAMP = 4.0

    # Memory guardrails for this 7900 XT rig.
    VRAM_SOFT_LIMIT_GB = 16.0
    VRAM_EMERGENCY_LIMIT_GB = 18.0
    VRAM_PROACTIVE_CLEAR_GB = 15.0
    CACHE_CLEAR_INTERVAL_ITERS = 25
    RAM_SOFT_LIMIT_PCT = 85.0
    RECOVERY_VRAM_PCT = 0.72
    RECOVERY_RAM_MARGIN = 8.0
    MEMORY_BACKOFF_COOLDOWN_ITERS = 5
    RUNTIME_ERROR_BACKOFF_COOLDOWN_ITERS = 10
    BACKOFF_COOLDOWN = MEMORY_BACKOFF_COOLDOWN_ITERS
    CACHE_CLEAR_INTERVAL = CACHE_CLEAR_INTERVAL_ITERS

    # Storage and checkpointing.
    CHECKPOINT_INTERVAL = 100
    CHECKPOINT_DIR = 'checkpoints'
    LATEST_CHECKPOINT_NAME = 'checkpoint_latest.pt'
    BEST_CHECKPOINT_NAME = 'checkpoint_best.pt'
    STORAGE_DIR = 'storage'
    REPLAY_BUFFER_SIZE = 1_000_000
    REPLAY_WARMUP_SAMPLES = 4096
    LMDB_MAP_SIZE_GB = 16
    MAX_LMDB_MAP_SIZE_GB = 30
    PPO_REPLAY_ENABLED = False

    # Background equity model refresh.
    EQUITY_TRAINING_ENABLED = False
    EQUITY_TRAIN_INTERVAL = 1000
    EQUITY_TRAIN_EPOCHS = 4
    EQUITY_TRAIN_STEPS_PER_EPOCH = 50
    EQUITY_TRAIN_BATCH_SIZE = 256
    EQUITY_TRAIN_VALIDATION_BATCH_SIZE = 128
    EQUITY_TRAIN_VALIDATION_BATCHES = 4

    # Multiprocessing and workers.
    MP_PROCESSES = STABLE_MP_PROCESSES

    # Smoke-test profile.
    SMOKE_TEST_ITERATIONS = 4
    SMOKE_TEST_BATCH_SIZE = 4096
    SMOKE_TEST_NUM_SIMULATIONS = 128
    SMOKE_TEST_ROLLOUT_STEPS = 64
    SMOKE_TEST_VALIDATION_INTERVAL = 2
    SMOKE_TEST_LOG_INTERVAL = 1
    SMOKE_TEST_CHECKPOINT_INTERVAL = 2

    # Medium GPU validation profile for the 7900 XT rig.
    MEDIUM_RUN_ITERATIONS = 500
    MEDIUM_RUN_BATCH_SIZE = 12288
    MEDIUM_RUN_NUM_SIMULATIONS = 256
    MEDIUM_RUN_HIDDEN_DIM = 2560
    MEDIUM_RUN_ROLLOUT_STEPS = 512
    MEDIUM_RUN_LOG_INTERVAL = 20
    MEDIUM_RUN_VALIDATION_INTERVAL = 500
    MEDIUM_RUN_NUM_TRAINING_STEPS = 24
    MEDIUM_RUN_REPLAY_BUFFER_SIZE = 2_000_000
    MEDIUM_RUN_LMDB_MAP_SIZE_GB = 30
    MEDIUM_RUN_ENTROPY_COEF = 0.025
    MEDIUM_RUN_ENTROPY_FINAL_COEF = 0.008
    MEDIUM_RUN_ENTROPY_DECAY_ITERS = 20000
    MEDIUM_RUN_POPULATION_MIX_PROB = 0.15
    MEDIUM_RUN_MCTS_DEPTH = 80
    MEDIUM_RUN_PPO_REPLAY_ENABLED = True
    MEDIUM_RUN_VALUE_CLIP_ENABLED = True
    MEDIUM_RUN_EQUITY_TRAIN_INTERVAL = 600
    MEDIUM_RUN_MP_PROCESSES = STABLE_MP_PROCESSES
    MEDIUM_RUN_GRADIENT_ACCUMULATION_STEPS = 2

    # Stable-plus profile: larger than stable, smaller than medium, targets ~8-10 GB VRAM on 7900 XT.
    STABLE_PLUS_ITERATIONS = 100000
    STABLE_PLUS_BATCH_SIZE = 8192
    STABLE_PLUS_NUM_SIMULATIONS = 192
    STABLE_PLUS_HIDDEN_DIM = 2048
    STABLE_PLUS_ROLLOUT_STEPS = 512
    STABLE_PLUS_LOG_INTERVAL = 10
    STABLE_PLUS_VALIDATION_INTERVAL = 500
    STABLE_PLUS_NUM_TRAINING_STEPS = 16
    STABLE_PLUS_PPO_MINIBATCHES = 16
    STABLE_PLUS_GRADIENT_ACCUMULATION_STEPS = 2
    STABLE_PLUS_GRADIENT_CHECKPOINTING = False
    STABLE_PLUS_MCTS_DEPTH = 3
    STABLE_PLUS_PPO_REPLAY_ENABLED = False
    STABLE_PLUS_VRAM_SOFT_LIMIT_GB = 13.5
    STABLE_PLUS_MP_PROCESSES = 16
    STABLE_PLUS_CACHE_CLEAR_INTERVAL_STEPS = 1

    # Aggressive ROCm profile that scales actual PPO rollout throughput.
    AGGRESSIVE_RUN_ITERATIONS = 500000
    AGGRESSIVE_RUN_BATCH_SIZE = 16384
    AGGRESSIVE_RUN_NUM_SIMULATIONS = 1024
    AGGRESSIVE_RUN_HIDDEN_DIM = 4096
    AGGRESSIVE_RUN_ROLLOUT_STEPS = 2048
    AGGRESSIVE_RUN_MAX_ROLLOUT_STEPS = 2048
    AGGRESSIVE_RUN_LOG_INTERVAL = 20
    AGGRESSIVE_RUN_VALIDATION_INTERVAL = 2000
    AGGRESSIVE_RUN_NUM_TRAINING_STEPS = 64
    AGGRESSIVE_RUN_GRADIENT_ACCUMULATION_STEPS = 4
    AGGRESSIVE_RUN_PPO_MINIBATCHES = 4
    AGGRESSIVE_RUN_GRADIENT_CHECKPOINTING = False
    AGGRESSIVE_RUN_USE_TORCH_COMPILE = False
    AGGRESSIVE_RUN_VRAM_SOFT_LIMIT_GB = 13.0
    AGGRESSIVE_RUN_RAM_SOFT_LIMIT_PCT = 80.0
    AGGRESSIVE_RUN_ROLLOUT_SCALE_WITH_BATCH = False
    AGGRESSIVE_RUN_REPLAY_BUFFER_SIZE = 10_000_000
    AGGRESSIVE_RUN_LMDB_MAP_SIZE_GB = 30
    AGGRESSIVE_RUN_LEARNING_RATE = 3e-5
    AGGRESSIVE_RUN_ENTROPY_COEF = 0.015
    AGGRESSIVE_RUN_ENTROPY_FINAL_COEF = 0.001
    AGGRESSIVE_RUN_ENTROPY_DECAY_ITERS = 20000
    AGGRESSIVE_RUN_POPULATION_MIX_PROB = 0.15
    AGGRESSIVE_RUN_MCTS_DEPTH = 2
    AGGRESSIVE_RUN_MCTS_TRIGGER_PROB = 0.05
    AGGRESSIVE_RUN_PPO_REPLAY_ENABLED = True
    AGGRESSIVE_RUN_VALUE_CLIP_ENABLED = True
    AGGRESSIVE_RUN_EQUITY_TRAIN_INTERVAL = 1200
    AGGRESSIVE_RUN_MP_PROCESSES = 20
    AGGRESSIVE_WARMUP_ITERS = 5000
    AGGRESSIVE_WARMUP_MIN_ROLLOUT_STEPS = 256
    AGGRESSIVE_WARMUP_MIN_NUM_SIMULATIONS = 256
    AGGRESSIVE_WARMUP_MIN_TRAINING_STEPS = 16

    # Optional long unattended run profile.
    LONG_RUN_ITERATIONS = 500000

    EQUITY_FEATURE_DIM = 106
    EQUITY_HIDDEN_DIM = 256
    EQUITY_MODEL = EquityNet(EQUITY_FEATURE_DIM, EQUITY_HIDDEN_DIM).to(DEVICE)
    EQUITY_MODEL.eval()


if os.path.exists('best_equity_model.pth'):
    try:
        Config.EQUITY_MODEL.load_state_dict(torch.load('best_equity_model.pth', map_location=Config.DEVICE, weights_only=True))
    except Exception:
        pass